$str = "Welcomde to \ntutorialspoint.com!";
print "$str\n";
$str = 'Welcomde to \ntutorialspoint.com!';
print "$str\n";
$str = "\UWelcome to tutorialspoint.com!";
print "$str\n";
$str = "\uWelcome to tutorialspoint.com!";
print "$str\n";
$str = "Welcome to \ututorialspoint.com!";
print "$str\n";
$str = "\QWelcome to tutorialspoint.com!";
print "$str\n";
