file = open("/home/madisnit/Desktop/example.txt","w")
file.write("dahbja ajbdajd a \n")
file.write("dahbja ajbdajd a \n")
file.write("dahbja ajbdajd a \n")
file.write("dahbja ajbdajd a \n")
file.close()
